name: ai_chat_scroll_example
description: Example app for the ai_chat_scroll package.
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  ai_chat_scroll:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
